chezmoi:
- ~/.config/archdots
- ~/Documents/WindowsPowerShell
ignored_pkgs:
  winget:
  - Microsoft.VCLibs.14
  - Microsoft.VCLibs.Desktop.14
  - Microsoft.VCRedist.2015+.x64
  - Microsoft.WindowsAppRuntime.1.8
  - Microsoft.UI.Xaml.2.8
pkgs:
  scoop:
  - chezmoi
  winget:
  - chrisant996.Clink
  - Vivaldi.Vivaldi
  - Microsoft.WindowsTerminal
  - Neovim.Neovim
  - Git.Git
  - Starship.Starship
  - jasongin.nvs
  - qBittorrent.qBittorrent
  - Vencord.Vesktop
  - GitHub.cli
  - Microsoft.VisualStudioCode
  - Oven-sh.Bun
  - Microsoft.AppInstaller
  - Microsoft.PowerShell
  - ajeetdsouza.zoxide
